version: "3.7"
services:
    db:
        image: "mysql:5.7"
        volumes:
            - db_data:/var/lib/mysql
        environment: 
          MYSQL_ROOT_PASSWORD: rootp@ss
          MYSQL_USER: user1
          MYSQL_PASSWORD: user1p@ss
volumes:
  db_data: